import { Game, ITEM_CHECK_VARIANT_VERIFY } from './data'
import { randomColor } from './utils'

export const defaultGame: Game = {
  ticks: 0,
  sceneName: 'room',
  previousSceneName: 'room',
  roomName: 'quarters-a',
  characteristicLabels: {
    strength: 'Strength',
    dexterity: 'Dexterity',
    endurance: 'Endurance',
    intelligence: 'Intelligence',
    education: 'Education',
    socialStanding: 'Social Standing',
    psionicStrength: 'Psionic Strength',
  },
  skillLabels: {
    groundVehicle: 'Ground Vehicle',
    gunCombat: 'Gun Combat',
    mechanics: 'Mechanics',
    slugPistol: 'Slug Pistol',
    vehicle: 'Vehicle',
  },
  rooms: [
    {
      name: 'quarters-a',
      title: 'Quarters A',
      exits: [{ name: 'north', title: 'north', to: 'hallway' }],
      entities: ['alard-tyney', 'terminal-1'],
      tags: ['description:fix-1:success'],
    },
    {
      name: 'quarters-b',
      title: 'Quarters B',
      exits: [{ name: 'south', title: 'south', to: 'hallway' }],
      entities: ['beth-raschke', 'nikos-rosek'],
      tags: ['description:fix-1:success'],
    },
    {
      name: 'hallway',
      title: 'Hallway',
      exits: [
        { name: 'north', title: 'north', to: 'quarters-b' },
        { name: 'south', title: 'south', to: 'quarters-a' },
        { name: 'east', title: 'east', to: 'bridge' },
        { name: 'west', title: 'west', to: 'galley' },
      ],
      entities: [],
      tags: [],
    },
    {
      name: 'bridge',
      title: 'Bridge',
      exits: [{ name: 'west', title: 'west', to: 'hallway' }],
      entities: [],
      tags: [],
    },
    {
      name: 'galley',
      title: 'Galley',
      exits: [{ name: 'east', title: 'east', to: 'hallway' }],
      entities: ['kynon-morgan'],
      tags: [],
    },
  ],
  partyRepresentativeName: 'alard-tyney',
  party: ['arlen-hyden', 'alice-hewitt'],
  entityName: null,
  entities: [
    {
      name: 'arlen-hyden',
      title: 'Arlen Hyden',
      color: randomColor(),
      tags: ['character', 'offensive'],
      characteristics: {
        strength: 6,
        dexterity: 10,
        endurance: 9,
        intelligence: 8,
        education: 5,
        socialStanding: 7,
        psionicStrength: 0,
      },
      skills: {
        mechanics: 0,
        gunCombat: 0,
        slugPistol: 1,
        vehicle: 0,
        groundVehicle: 0,
      },
      inventory: ['revolver-1'],
    },
    {
      name: 'alice-hewitt',
      title: 'Alice Hewitt',
      color: randomColor(),
      tags: ['character', 'offensive'],
      characteristics: {
        strength: 6,
        dexterity: 10,
        endurance: 9,
        intelligence: 8,
        education: 5,
        socialStanding: 7,
        psionicStrength: 0,
      },
      skills: {
        mechanics: 0,
        gunCombat: 0,
        slugPistol: 1,
        vehicle: 0,
        groundVehicle: 0,
      },
      inventory: ['revolver-2'],
    },
    {
      name: 'beth-raschke',
      title: 'Beth Raschke',
      color: randomColor(),
      tags: ['character', 'ally:nikos-rosek', 'hostile', 'offensive'],
      characteristics: {
        strength: 6,
        dexterity: 10,
        endurance: 9,
        intelligence: 8,
        education: 5,
        socialStanding: 7,
        psionicStrength: 0,
      },
      skills: {
        mechanics: 0,
        gunCombat: 0,
        slugPistol: 1,
        vehicle: 0,
        groundVehicle: 0,
      },
      inventory: ['revolver-3'],
    },
    {
      name: 'nikos-rosek',
      title: 'Nikos Rosek',
      color: randomColor(),
      tags: ['character', 'ally:beth-raschke', 'hostile', 'offensive'],
      characteristics: {
        strength: 6,
        dexterity: 10,
        endurance: 9,
        intelligence: 8,
        education: 5,
        socialStanding: 7,
        psionicStrength: 0,
      },
      skills: {
        mechanics: 0,
        gunCombat: 0,
        slugPistol: 1,
        vehicle: 0,
        groundVehicle: 0,
      },
      inventory: ['revolver-4'],
    },
    {
      name: 'alard-tyney',
      title: 'Alard Tyney',
      color: randomColor(),
      tags: [
        'character',
        'dialogue:alard-1:0',
        'skill-check:alard-1',
        'skill-check:alard-2',
        'description:alard-1:success',
        'description:alard-1:failure',
        'offensive',
      ],
      characteristics: {
        strength: 6,
        dexterity: 10,
        endurance: 9,
        intelligence: 8,
        education: 5,
        socialStanding: 7,
        psionicStrength: 0,
      },
      skills: {
        mechanics: 0,
        gunCombat: 0,
        slugPistol: 1,
        vehicle: 0,
        groundVehicle: 0,
      },
      inventory: ['revolver-5'],
    },
    {
      name: 'kynon-morgan',
      title: 'Kynon Morgan',
      color: randomColor(),
      tags: [
        'character',
        'wandering',
        'choice:birds-1',
        'item-check:has-revolver-1',
      ],
      characteristics: {
        strength: 10,
        dexterity: 6,
        endurance: 5,
        intelligence: 7,
        education: 9,
        socialStanding: 8,
        psionicStrength: 0,
      },
      skills: {
        mechanics: 0,
        gunCombat: 0,
        slugPistol: 1,
        vehicle: 0,
        groundVehicle: 0,
      },
      inventory: ['knife-1'],
    },
    {
      name: 'terminal-1',
      title: 'Terminal',
      color: randomColor(),
      inventory: [],
      tags: [
        'skill-check:fix-1',
        'description:fix-1:success',
        'description:fix-1:failure',
      ],
    },
  ],
  items: [
    {
      name: 'revolver-1',
      title: 'Revolver',
      rounds: 6,
      tags: ['ranged'],
      damage: '2d6',
      isEquipped: true,
    },
    {
      name: 'revolver-2',
      title: 'Revolver',
      rounds: 6,
      tags: ['ranged'],
      damage: '2d6',
      isEquipped: true,
    },
    {
      name: 'revolver-3',
      title: 'Revolver',
      rounds: 6,
      tags: ['ranged'],
      damage: '2d6',
      isEquipped: true,
    },
    {
      name: 'revolver-4',
      title: 'Revolver',
      rounds: 6,
      tags: ['ranged'],
      damage: '2d6',
      isEquipped: true,
    },
    {
      name: 'revolver-5',
      title: 'Revolver',
      rounds: 6,
      tags: ['ranged'],
      damage: '2d6',
      isEquipped: true,
    },
    {
      name: 'revolver-6',
      title: 'Revolver',
      rounds: 6,
      tags: ['ranged'],
      damage: '2d6',
      isEquipped: true,
    },
    {
      name: 'knife-1',
      title: 'Knife',
      rounds: null,
      tags: ['melee'],
      damage: '1d6',
      isEquipped: true,
    },
  ],
  dialogues: [
    {
      name: 'alard-1',
      conditionTag: null,
      topic: `what's on my mind`,
      stringKeys: [
        'dialogues.alard-1.0',
        'dialogues.alard-1.1',
        'dialogues.alard-1.2',
      ],
    },
  ],
  skillCheckName: null,
  skillChecks: [
    {
      name: 'fix-1',
      conditionTag: null,
      title: 'Repair the broken terminal?',
      characteristic: 'intelligence',
      skill: 'mechanics',
      dice: '2d6',
      tn: 8,
      result: null,
    },
    {
      name: 'alard-1',
      conditionTag: 'dialogue:alard-1:done',
      title: 'Do you think you could give me some guidance?',
      characteristic: 'education',
      skill: 'mechanics',
      dice: '2d6',
      tn: 8,
      result: null,
    },
    {
      name: 'alard-2',
      conditionTag: 'skill-check:alard-1:failure',
      title: 'Do you want to try again?',
      characteristic: 'education',
      skill: 'mechanics',
      dice: '2d6',
      tn: 6,
      result: null,
    },
  ],
  itemCheckName: null,
  itemChecks: [
    {
      name: 'has-revolver-1',
      conditionTag: null,
      title: 'Do you have the gun?',
      stringKey: 'itemChecks.has-revolver-1',
      variant: { type: ITEM_CHECK_VARIANT_VERIFY },
      itemName: 'revolver-5',
    },
  ],
  partyCheckName: null,
  partyChecks: [],
  battleCheckName: null,
  battleChecks: [],
  choiceName: null,
  choices: [
    {
      name: 'birds-1',
      title: 'A quick question about birds',
      conditionTag: null,
      stringKey: 'choices.birds-1.question',
      options: [
        {
          name: 'birds-1:yes',
          stringKey: 'choice.birds-1.yes',
        },
        {
          name: 'birds-1:no',
          stringKey: 'choice.birds-1.no',
        },
      ],
    },
  ],
  descriptions: [
    {
      name: 'birds-1:yes',
      conditionTag: 'birds-1:yes',
      stringKey: 'descriptions.birds-1.yes',
    },
    {
      name: 'birds-1:no',
      conditionTag: 'birds-1:no',
      stringKey: 'descriptions.birds-1.no',
    },
    {
      name: 'alard-1:success',
      conditionTag: 'skill-check:alard-1:success',
      stringKey: 'descriptions.alard-1.success',
    },
    {
      name: 'alard-1:failure',
      conditionTag: 'skill-check:alard-1:failure',
      stringKey: 'descriptions.alard-1.failure',
    },
    {
      name: 'fix-1:success',
      conditionTag: 'skill-check:fix-1:success',
      stringKey: 'descriptions.fix-1.success',
    },
    {
      name: 'fix-1:failure',
      conditionTag: 'skill-check:fix-1:failure',
      stringKey: 'descriptions.fix-1.failure',
    },
  ],
  fieldName: null,
  fields: [],
  strings: {
    en: {
      sample: {
        message: 'Hello, *<%= name %>*!',
      },
      choices: {
        'birds-1': {
          question: 'Do you like birds?',
          yes: 'Yes',
          no: 'No',
        },
      },
      descriptions: {
        'birds-1': {
          yes: '',
          no: '',
        },
        'alard-1': {
          yes: '',
          no: '',
        },
        'fix-1': {
          yes: '',
          no: '',
        },
      },
      dialogues: {
        'alard-1': {
          '0': 'One...',
          '1': 'Two...',
          '2': 'Three...',
        },
      },
      itemChecks: {
        'has-revolver-1': 'Looks like you have it.',
      },
    },
  },
}
